package com.calendario.ui;

/**
 *
 * @author anclenius
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.grupoDeBotones.add(calendarioHaab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        calendarioHaab = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        calendrioCholqijRadioButton1 = new javax.swing.JRadioButton();
        matrizHaab = new javax.swing.JRadioButton();
        sumadorFechas = new javax.swing.JRadioButton();
        aceptarOpcionButton = new javax.swing.JButton();
        calendarioLunar = new javax.swing.JRadioButton();
        matrizLunar = new javax.swing.JRadioButton();
        matrizCholquij = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calendarios Mayas");

        calendarioHaab.setText("Calendario Haab");

        jLabel2.setText("Seleccione la aplicacion a usar");

        calendrioCholqijRadioButton1.setText("Nahual y energia Cholqij");

        matrizHaab.setText("Matriz Haab");
        matrizHaab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizHaabActionPerformed(evt);
            }
        });

        sumadorFechas.setText("Sumador Fechas");

        aceptarOpcionButton.setText("Aceptar");
        aceptarOpcionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarOpcionButtonActionPerformed(evt);
            }
        });

        calendarioLunar.setText("Calendario Lunar");
        calendarioLunar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioLunarActionPerformed(evt);
            }
        });

        matrizLunar.setText("Matriz Lunar");

        matrizCholquij.setText("Matriz Cholqij");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matrizLunar)
                    .addComponent(jLabel2)
                    .addComponent(calendrioCholqijRadioButton1)
                    .addComponent(calendarioHaab, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matrizHaab, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sumadorFechas))
                        .addGap(84, 84, 84)
                        .addComponent(aceptarOpcionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calendarioLunar)
                    .addComponent(matrizCholquij))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendrioCholqijRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarioHaab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(matrizHaab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sumadorFechas))
                    .addComponent(aceptarOpcionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarioLunar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matrizLunar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matrizCholquij)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarOpcionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarOpcionButtonActionPerformed
        if (this.calendrioCholqijRadioButton1.isSelected()) {
            CholqijFrame ch = new CholqijFrame();
            ch.setVisible(true);
            this.dispose();
        } else if (calendarioHaab.isSelected()) {
            HaabFrame haab = new HaabFrame();
            haab.setBounds(500, 300, 1000, 500);
            haab.setVisible(true);
            this.dispose();
        } else if (matrizHaab.isSelected()){
            MatrizHaabFrame matrizHaab = new MatrizHaabFrame();
            matrizHaab.setVisible(true);
            this.dispose();
        }else if (sumadorFechas.isSelected()){
            FechasUI fecha = new FechasUI();
            fecha.setBounds(500, 300, 1000, 500);
            fecha.setVisible(true);
            this.dispose();
        }else if (calendarioLunar.isSelected()){
            Calendario2019 fecha = new Calendario2019(this);
            fecha.setBounds(500, 300, 1000, 500);
            fecha.setVisible(true);
            this.dispose();
        }else if (matrizLunar.isSelected()){
            FrameMatrizLunar fecha = new FrameMatrizLunar(this);
            fecha.setBounds(500, 300, 1000, 500);
            fecha.setVisible(true);
            this.dispose();
        }else if (matrizCholquij.isSelected()) {
            matrizCholquijFrame matrizChol = new matrizCholquijFrame();
            matrizChol.setBounds(500, 300, 1000, 500);
            matrizChol.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_aceptarOpcionButtonActionPerformed

    private void matrizHaabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizHaabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizHaabActionPerformed

    private void calendarioLunarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioLunarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioLunarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarOpcionButton;
    private javax.swing.JRadioButton calendarioHaab;
    private javax.swing.JRadioButton calendarioLunar;
    private javax.swing.JRadioButton calendrioCholqijRadioButton1;
    private javax.swing.ButtonGroup grupoDeBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton matrizCholquij;
    private javax.swing.JRadioButton matrizHaab;
    private javax.swing.JRadioButton matrizLunar;
    private javax.swing.JRadioButton sumadorFechas;
    // End of variables declaration//GEN-END:variables
}
