/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.calendario.ui;

import com.ElementosCalendarioHaab.FechaHaab;
import com.Haab.ManejadorCalendarioHaab;
import com.Haab.ManejadorMatrizHaab;
import javax.swing.table.DefaultTableModel;
import com.ElementosCalendarioHaab.FechaHaab;
import com.ElementosCalendarioHaab.HaabUi.Meses;
import com.Haab.ManejadorCalendarioHaab;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextPane;

/**
 *
 * @author fabricio
 */
public class MatrizHaabFrame extends javax.swing.JFrame {

    private ManejadorMatrizHaab manejador;
    public static final int NUM_DAYS = 20;
    public static final int NUM_MONTHS = 19;
    private String selectedDate = null;
    public static final String FRAME_TITLE = "Matriz Haab";

    /**
     * Creates new form MatrizHaab
     */
    public MatrizHaabFrame() {
        manejador = new ManejadorMatrizHaab(this);
        initComponents();
        this.setTitle(FRAME_TITLE);
        this.setLocationRelativeTo(this);
        setVisiblePanel(false);
        manejador.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHaab = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelMes = new javax.swing.JLabel();
        panelDia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Matriz Haab");

        tableHaab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            manejador.columnsName()
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHaab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHaabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHaab);
        if (tableHaab.getColumnModel().getColumnCount() > 0) {
            tableHaab.getColumnModel().getColumn(0).setResizable(false);
            tableHaab.getColumnModel().getColumn(1).setResizable(false);
            tableHaab.getColumnModel().getColumn(2).setResizable(false);
            tableHaab.getColumnModel().getColumn(3).setResizable(false);
            tableHaab.getColumnModel().getColumn(5).setResizable(false);
            tableHaab.getColumnModel().getColumn(6).setResizable(false);
            tableHaab.getColumnModel().getColumn(7).setResizable(false);
            tableHaab.getColumnModel().getColumn(8).setResizable(false);
            tableHaab.getColumnModel().getColumn(9).setResizable(false);
            tableHaab.getColumnModel().getColumn(10).setResizable(false);
            tableHaab.getColumnModel().getColumn(11).setResizable(false);
            tableHaab.getColumnModel().getColumn(12).setResizable(false);
            tableHaab.getColumnModel().getColumn(13).setResizable(false);
            tableHaab.getColumnModel().getColumn(14).setResizable(false);
            tableHaab.getColumnModel().getColumn(15).setResizable(false);
            tableHaab.getColumnModel().getColumn(16).setResizable(false);
            tableHaab.getColumnModel().getColumn(17).setResizable(false);
            tableHaab.getColumnModel().getColumn(18).setResizable(false);
        }

        jPanel1.setForeground(new java.awt.Color(1, 1, 1));

        jLabel2.setText("MES");

        jLabel3.setText("DIA");

        jLabel4.setText("INFORMACION");

        infoArea.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(infoArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelMes, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(panelDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(469, 469, 469))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableHaabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHaabMouseClicked
        manejador.procesarMatriz();
    }//GEN-LAST:event_tableHaabMouseClicked

    public String getSelectedDate() {
        return selectedDate;
    }

    public void setSelectedDate(String selectedDate) {
        this.selectedDate = selectedDate;
    }

    public void setVisiblePanel(boolean state){
        this.jPanel1.setVisible(state);
    } 

    public JLabel getPanelDia() {
        return panelDia;
    }

    public JLabel getPanelMes() {
        return panelMes;
    }

    public JTable getTableHaab() {
        return tableHaab;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JTextPane getInfoArea() {
        return infoArea;
    }

    public void setInfoArea(JTextPane infoArea) {
        this.infoArea = infoArea;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane infoArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel panelDia;
    private javax.swing.JLabel panelMes;
    private javax.swing.JTable tableHaab;
    // End of variables declaration//GEN-END:variables
}
